config/routes.rb
AnimalTransporterPlus::Application.routes.draw do

  # For authentication system
  resources :users do
    resource :address
    resources :rescue_groups
    resources :shelters
    resources :transporters
  end
  resources :sessions

  # Listed in downward spiral order of operations. Ex: Shelter(s) have Animal(s) the Puller(s) get
  # and give to the RescueGroup(s) who create Trip(s), made of Leg(s) and Transporter(s), in order
  # to get the Animal(s) to Adopter(s).

  resources :rescue_groups do
    resources :adopters
    resources :shelters
    resources :animals do
      resources :shelters
      resource  :adopter
    end
    resources :pullers
    resources :transporters
    resources :trips do
      resources :legs
    end
  end

  # Dashboard for each user. This will be scoped to A) the particular user, and B) their role
  resource :dashboard

  # Application root
  root 'pages#index', only: :get

  get "/about" => "pages#about"
  get "/services" => "pages#services"
  get "/equipment" => "pages#equipment"
  get "/register" => "users#new"
  get "/contact_us" => "pages#contact_us"
  get "/dashboard" => "dashboard#show"
  get '/account' => "pages#account"
  get '/login', to: 'sessions#new', as: 'login'
  get '/logout', to: 'sessions#destroy', as: 'logout'
end

app/models/shelter.rb
class Shelter < ActiveRecord::Base

  validates :name,
            :phone_number,
            :contact_person, presence: true

  has_many :animals, dependent: :destroy  # Has many animals obviously. Also deals with multiple rescue_groups
                                          # but RARELY deals with transporters. Thats the rescue_group's job.
                                          # Also, the shelter doesn't list the rescue_groups. its just that many
                                          # rescue_groups happen to deal with the same shelter.
  accepts_nested_attributes_for :animals, reject_if: :all_blank, allow_destroy: true

  has_one :address, dependent: :destroy
  accepts_nested_attributes_for :address

  belongs_to :rescue_group
end

app/controllers/shelters_controller.rb
class SheltersController < ApplicationController
  def index
    @rescue_group = RescueGroup.find(params[:rescue_group_id])

    @shelters = @rescue_group.shelters.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @shelters }
    end
  end

  def show
    @shelter = Shelter.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @shelter }
    end
  end

  def new
    # We only pass in rescue_group_id. So have to get the right rescue first
    @rescue_group = RescueGroup.find(params[:rescue_group_id])

    # Now this should all work
    @shelter = @rescue_group.shelters.new
    @shelter.build_address
    @shelter.animals.build

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @shelter }
    end
  end

  def create
    @rescue_group = RescueGroup.find(params[:rescue_group_id])

    @shelter = @rescue_group.shelters.create(params[:shelter])

    if @shelter.valid? == true  && @shelter.save!
      respond_to do |format|
        format.html { redirect_to rescue_group_shelters_path(@rescue_group), notice: "Shelter #{@shelter.name} was successfully created." }
        format.xml  { render :xml => @shelter, :status => :created, :location => @shelter }
      end
    else
      flash[:error] = 'OOPS! Shelter failed to create.'
      render action: 'new'
    end
  end

  def update
    @shelter = Shelter.find(params[:id])

    respond_to do |format|
      if @shelter.valid? == true && @shelter.update_attributes(params[:shelter])
        flash[:notice] = 'Successfully updated Shelter!'
        format.html { redirect_to(@shelter) }
        format.xml  { head :ok }
      else
        flash.now[:error] = "OOPS! Shelter could not be updated."
        flash[:error] = "OOPS! Shelter could not be updated."
        format.html { render :action => "edit" }
        format.xml  { render :xml => @shelter.errors, :status => :unprocessable_entity }
      end
    end
  end

  def edit
    @shelter = Shelter.find(params[:id])
  end

  def destroy
    @shelter = Shelter.find(params[:id])
    @shelter.destroy

    respond_to do |format|
      flash[:notice] = 'Shelter successfully deleted!'
      format.html { redirect_to(rescue_group_shelters_path(@shelter.rescue_group_id)) }
      format.xml  { head :ok }
    end
  end

  private

  def shelter_params
    params.require(:shelter).permit(:name, :phone_number, :contact_person, :rescue_group_id, :address_attributes[:id, :address1, :address2, :address3, :city, :state, :zip], :animals_attributes[:id, :species, :age, :weight, :sex, :breed, :altered, :aggressive, :health_certificate, :diseases, :shelter_id, :rescue_group_id, :adopter_id])
  end
end

app/helpers/shelters_helper.rb
module SheltersHelper
end

app/views/shelters/delete.html.erb
<h1>Shelters#destroy</h1>
<p>Find me in app/views/shelters/destroy.html.erb</p>

app/views/shelters/edit.html.erb
<h1>Shelters#edit</h1>
<p>Find me in app/views/shelters/edit.html.erb</p>

app/views/shelters/index.html.erb
<div class="panel panel-primary">
  <div class="panel-heading"><h3 class="panel-title">Animal Shelters</h3></div>
  <div class="panel body"></div>
  <!-- shelter table listing all existing shelters -->
  <table class="shelters_table">
    <tr>
      <th>Name</th>
      <th>Number</th>
      <th>Person</th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
    <% @shelters.each do |shelter| %>
    <tr>
      <td><%= shelter.name %></td>
      <td><%= shelter.phone_number %></td>
      <td><%= shelter.contact_person %></td>
      <td>&nbsp;</td>
      <td><%= link_to "Show", rescue_group_shelter_path(@rescue_group, shelter) %></td>
      <td><%= link_to "Edit", edit_rescue_group_shelter_path(@rescue_group, shelter) %></td>
      <td><%= link_to "Delete", rescue_group_shelter_path(@rescue_group, shelter), method: :delete, data: { confirm: "Are you sure?" } %></td>
    </tr>
  <% end %>
  </table>
  <br />
  <div class="panel-info" align="center"><%= link_to "Create a New Shelter", new_rescue_group_shelter_path(@rescue_group) %> - <%= link_to "Return to Dashboard", dashboard_path %></div>
  <div class="panel-footer">Copyright &copy; 2013 D Deryl Downey. All Rights Reserved.</div>
</div>

app/views/shelters/new.html.erb
<h1>New Shelter</h1>
<%= form_for [@rescue_group, @shelter], signed: true do |f| %>
    <% if @shelter.errors.any? %>
      <div class="panel panel-danger">
        <ul>
          <% @shelter.errors.full_messages.each do |err_msg| %>
            <li><%= err_msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <p>
      <%= f.label :name, "Full Name" %>
      <%= f.text_field :name %><br />
    </p>

    <p>
      <%= f.label :phone_number, 'Phone Number' %>
      <%= f.text_field :phone_number %><br />
    </p>

    <p>
      <%= f.label :contact_person, 'Contact Person' %>
      <%= f.text_field :contact_person %><br />
    </p>

    <h3>Address</h3>
    <%= f.fields_for :address do |builder| %>
        <p>
          <%= builder.label :address1, "Address Line 1" %>
          <%= builder.text_field :address1 %><br />
          <%= builder.label :address2, "Address Line 2" %>
          <%= builder.text_field :address2 %><br />
          <%= builder.label :address3, "Address Line 3" %>
          <%= builder.text_field :address3 %><br />
          <%= builder.label :city, "City" %>
          <%= builder.text_field :city %><br />
          <%= builder.label :state, "State" %>
          <%= builder.text_field :state %><br />
          <%= builder.label :zip, "Zip Code" %>
          <%= builder.text_field :zip %><br />
        </p>
    <% end %>

    <h3>Animal</h3>
    <%= f.fields_for :animals do |builder| %>
        <p>
          <%= render "animals/form", :f => builder %>
        </p>
    <% end %>
  <%= f.submit %>
<% end %>

app/views/shelters/show.html.erb
<h2><%= title(@shelter.name, "Shelters") %></h2>
<p>
  <strong>Shelter Name:</strong> <%= @shelter.name %><br/>
  <strong>Contact:</strong> <%= @shelter.contact_person %><br/>
  <strong>Phone Number:</strong> <%= @shelter.phone_number %><br />
  <strong>Address:</strong><br />

  <!-- Now, some of the following fields can be either nil or blank.
       So, we are going to check for both conditions and only display
       those fields that actually contain displayable data.
  -->
  <% %w[address1 address2 address3].each do |line| %>
    <% unless @shelter.address.send(line.to_sym).nil? || @shelter.address.send(line.to_sym).blank? %>
      <%= "#{@shelter.address.send(line.to_sym)}" %><br />
    <% end %>
  <% end %>

  <!-- These fields are Model validated fields. They *will* be in the db
       since the Address model won't save w/o them the first place. 
       We're keeping them on the same line since they would be on an envelope
  -->
  <% %w[city state zip].each do |line| %>
    <%= "#{@shelter.address.send(line.to_sym)}" %>
  <% end %>
  <br />
</p>

<p>
<%= link_to "Go to Dashboard", dashboard_path %>
</p>

app/views/shelters/update.html.erb
<h1>Shelters#update</h1>
<p>Find me in app/views/shelters/update.html.erb</p>