config/routes.rb
AnimalTransporterPlus::Application.routes.draw do

  # For authentication system
  resources :users do
    resource :address
    resources :rescue_groups
    resources :shelters
    resources :transporters
  end
  resources :sessions

  # Listed in downward spiral order of operations. Ex: Shelter(s) have Animal(s) the Puller(s) get
  # and give to the RescueGroup(s) who create Trip(s), made of Leg(s) and Transporter(s), in order
  # to get the Animal(s) to Adopter(s).

  resources :rescue_groups do
    resources :adopters
    resources :shelters
    resources :animals do
      resources :shelters
      resource  :adopter
    end
    resources :pullers
    resources :transporters
    resources :trips do
      resources :legs
    end
  end

  # Dashboard for each user. This will be scoped to A) the particular user, and B) their role
  resource :dashboard

  # Application root
  root 'pages#index', only: :get

  get "/about" => "pages#about"
  get "/services" => "pages#services"
  get "/equipment" => "pages#equipment"
  get "/register" => "users#new"
  get "/contact_us" => "pages#contact_us"
  get "/dashboard" => "dashboard#show"
  get '/account' => "pages#account"
  get '/login', to: 'sessions#new', as: 'login'
  get '/logout', to: 'sessions#destroy', as: 'logout'
end

app/models/rescue_group.rb
class RescueGroup < ActiveRecord::Base

  validates :name,
            :email_address,
            :contact,
            :emergency_contact, presence: true

  validates :phone_number, presence: true, format: { with: /\A\d{3}\-(\d{3})-(\d{4})\Z/, message: "must be in the format of 555-555-1212" }

  has_one :address, dependent: :destroy
  accepts_nested_attributes_for :address

  belongs_to :user
  has_many :shelters     # Each rescue_group usually deals with multiple shelters

  has_many :animals      # RescueGroups obviously deal with many animals. Each animal
                         # needs to have which rescue_group it came from originally,
                         # and, if needed, how many others were involved.

  has_many :pullers      # RescueGroups have people designated as (a) Puller(s) that go to the Shelter(s)
                         # to physically take control of the Animal(s).

  has_many :adopters, through: :animals # RescueGroups track Adopter(s) for Animal(s) through the Animal(s)

  has_many :trips # RescueGroups need to track Trip(s) in order to see where (a) Animal(s) went.

  has_and_belongs_to_many :transporters # A RescueGroup usually has many transporters associated with it
                                        # Note that (a) Transporter(s) can work with many RescueGroups
                                        # at the same time, showing on multiple RescueGroup rolls.

end

app/controllers/rescue_groups_controller.rb
class RescueGroupsController < ApplicationController
  def index
    @rescue_groups = RescueGroup.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @rescue_groups }
    end
  end

  def show
    @rescue_group = RescueGroup.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @rescue_group }
    end
  end

  def new
    @rescue_group = current_user.rescue_groups.new
    @rescue_group.build_address

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @rescue_group }
    end
  end

  def create
    @rescue_group = current_user.rescue_groups.create!(params[:rescue_group])

    respond_to do |format|
      if @rescue_group.save
        flash[:notice] = 'Rescue Group was successfully created.'
        format.html { redirect_to(@rescue_group) }
        format.xml  { render :xml => @rescue_group, :status => :created, :location => @rescue_group }
      else
        flash[:error] = 'OOPS! Rescue Group failed to create.'
        format.html { render :action => "new" }
        format.xml  { render :xml => @rescue_group.errors, :status => :unprocessable_entity }
      end
    end
  end

  def update
    @rescue_group = RescueGroup.find(params[:id])

    respond_to do |format|
      if @rescue_group.update_attributes(params[:rescue_group])
        flash[:notice] = 'Successfully updated Rescue Group!'
        format.html { redirect_to(@rescue_group) }
        format.xml  { head :ok }
      else
        flash[:error] = "OOPS! Rescue Group could not be updated."
        format.html { render :action => "edit" }
        format.xml  { render :xml => @rescue_group.errors, :status => :unprocessable_entity }
      end
    end
  end

  def edit
    @rescue_group = RescueGroup.find(params[:id])
  end

  def destroy
    @rescue_group = RescueGroup.find(params[:id])
    @rescue_group.destroy

    respond_to do |format|
      flash[:notice] = 'Rescue Group successfully deleted!'
      format.html { redirect_to(rescue_groups_url) }
      format.xml  { head :ok }
    end
  end

  private

  def rescue_group_params
      params.require(:rescue_group).permit(:name, :phone_number, :email_address,:contact, :emergency_contact, :address_attributes[:id, :address1, :address2, :address3, :city, :state, :zip, :user_id])
    end

end

app/helpers/rescue_groups_helper.rb
module RescueGroupsHelper
end

app/views/rescue_groups/delete.html.erb
<h1>RescueGroups#destroy</h1>
<p>Find me in app/views/rescue_groups/destroy.html.erb</p>

app/views/rescue_groups/edit.html.erb
<h1>RescueGroups#edit</h1>
<p>Find me in app/views/rescue_groups/edit.html.erb</p>

app/views/rescue_groups/index.html.erb
<h1><%= current_user.full_name %>'s Rescue Groups</h1>
<div class="panel panel-body">
  <% if current_user.rescue_groups.count != 0 then %>
    <div class="panel panel-default">
    <ul>
      <% current_user.rescue_groups.sort.each do |rg| %>
        <li><%= link_to "#{rg.name}", rescue_group_path(rg) %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<p><%= link_to "New Rescue Group", new_user_rescue_group_path(current_user) %> || <%= link_to "Return to Dashboard", dashboard_path, reload: true %></p>

app/views/rescue_groups/new.html.erb
<h1>New Rescue Group</h1>

<%= form_for [current_user, @rescue_group], signed: true do |f| %>
    <p>
      <%= f.label :name, "Name of Rescue" %>
      <%= f.text_field :name %><br />
    </p>

    <p>
      <%= f.label :phone_number, "Phone Number" %>
      <%= f.text_field :phone_number %><br />
    </p>

    <p>
      <%= f.label :email_address, "Email Address" %>
      <%= f.text_field :email_address %><br />
    </p>

    <p>
      <%= f.label :contact, "Primary Contact" %>
      <%= f.text_field :contact %><br />
    </p>

    <p>
      <%= f.label :emergency_contact, "Emergency Contact" %>
      <%= f.text_field :emergency_contact %><br />
    </p>

      <%= f.fields_for :address do |builder| %>
        <p>
            <%=	builder.label :address1, "Address Line 1" %>
            <%=	builder.text_field :address1 %><br />
            <%=	builder.label :address2, "Address Line 2" %>
            <%=	builder.text_field :address2 %><br />
            <%=	builder.label :address3, "Address Line 3" %>
            <%=	builder.text_field :address3 %><br />
            <%=	builder.label :city, "City" %>
            <%=	builder.text_field :city %><br />
            <%=	builder.label :state, "State" %>
            <%=	builder.text_field :state %><br />
            <%=	builder.label :zip, "Zip Code" %>
            <%=	builder.text_field :zip %><br />
        </p>
      <% end %>

    <%= f.submit %>

<% end %>

app/views/rescue_groups/show.html.erb
<h2><%= @rescue_group.name %></h2>
<p>
<div class="panel panel-info">
<div class="panel-heading">Account Info</div>

  <strong>ID#:</strong> <%= @rescue_group.id %><br />
  <strong>Joined: <%= @rescue_group.created_at %><br />
  <strong>Last Updated:</strong> <%= @rescue_group.updated_at %><br />
  <strong>Role:</strong> <%= current_user.role.titleize %>

</div>
</p>

<p>
<div class="panel panel-info">
<div class="panel-heading">Contact Info</div>

  <strong>Email Address:</strong> <%= mail_to(@rescue_group.email_address, "#{@rescue_group.email_address}",
                                             subject: "Rescue Group Contact") %><br/>
  <strong>Contact:</strong> <%= @rescue_group.contact %><br/>
  <strong>Phone Number:</strong> <%= @rescue_group.phone_number %><br />
  <strong>Emergency Contact:</strong> <%= @rescue_group.emergency_contact %><br/>

</div>
</p>

<p>
<% if @rescue_group.shelters.count != 0 then %>
  <div class="panel panel-info">
  <div class="panel-heading">Shelter Info</div>

  <% @rescue_group.shelters.each do |sh| %>
    <strong>Name:</strong> <%= link_to "#{sh.name}", rescue_group_shelter_path(sh, rescue_group_id: @rescue_group) %><br />
  <% end %>
  </div>
<% end %>
</p>

<p>
<div class="well">

  <%= link_to "* Add New Shelter", new_rescue_group_shelter_path(@rescue_group)%><br />
  <%= link_to "Go Back to Dashboard", dashboard_path(id: @rescue_group) %><br />

  </p>

app/views/rescue_groups/update.html.erb
<h1>RescueGroups#update</h1>
<p>Find me in app/views/rescue_groups/update.html.erb</p>