config/routes.rb
AnimalTransporterPlus::Application.routes.draw do

  # For authentication system
  resources :users do
    resource :address
    resources :rescue_groups
    resources :shelters
    resources :transporters
  end
  resources :sessions

  # Listed in downward spiral order of operations. Ex: Shelter(s) have Animal(s) the Puller(s) get
  # and give to the RescueGroup(s) who create Trip(s), made of Leg(s) and Transporter(s), in order
  # to get the Animal(s) to Adopter(s).

  resources :rescue_groups do
    resources :adopters
    resources :shelters
    resources :animals do
      resources :shelters
      resource  :adopter
    end
    resources :pullers
    resources :transporters
    resources :trips do
      resources :legs
    end
  end

  # Dashboard for each user. This will be scoped to A) the particular user, and B) their role
  resource :dashboard

  # Application root
  root 'pages#index', only: :get

  get "/about" => "pages#about"
  get "/services" => "pages#services"
  get "/equipment" => "pages#equipment"
  get "/register" => "users#new"
  get "/contact_us" => "pages#contact_us"
  get "/dashboard" => "dashboard#show"
  get '/account' => "pages#account"
  get '/login', to: 'sessions#new', as: 'login'
  get '/logout', to: 'sessions#destroy', as: 'logout'
end

app/models/address.rb
class Address < ActiveRecord::Base

  validates :address1,
           :city,
           :state,
           :zip, presence: true

  belongs_to :shelter
  belongs_to :rescue_group
  belongs_to :transporter
  belongs_to :puller
  belongs_to :adopter
  belongs_to :user

end

app/models/adopter.rb
class Adopter < ActiveRecord::Base

  validates :first_name,
            :last_name,
            :phone_number, presence: true

  validates_inclusion_of :vetted, :banned, in: [true, false]

  has_one :address, dependent: :destroy
  accepts_nested_attributes_for :address

  has_one :animal, through: :rescue_group, dependent: :destroy  # Usually, but not always, a single animal goes to a single adopter
  accepts_nested_attributes_for :animal                         # Not sure if has_one is appropriate due to edge case.

  belongs_to :rescue_group

end

app/models/animal.rb
class Animal < ActiveRecord::Base

  validates :species,
            :age,
            :sex,
            :breed,
            :diseases, presence: true


  validates_inclusion_of :altered, :aggressive, :health_certificate, in: [true, false]

  belongs_to :adopter        # Only one adopter is listed even if several will share the
                          # animal. That detail is for the adopters to figure out.

  belongs_to :rescue_group   # One rescue_group got the animal initially. Its only with the trip
                          # generally, that multiple rescue_groups get involved.
  belongs_to :shelter        # Each animal is rescued from a single shelter, obviously.

end

app/models/leg.rb
class Leg < ActiveRecord::Base

  has_one :start_address, foreign_key: "trip_id", class_name: "Address"
  has_one :end_address, foreign_key: "trip_id", class_name: "Address"

  validates :estimated_mileage, :actual_mileage, presence: true
  validates_inclusion_of :paid, in: [true, false]

  belongs_to :trip
  belongs_to :transporter

end

app/models/puller.rb
class Puller < ActiveRecord::Base

  validates :first_name,
            :last_name,
            :phone_number, presence: true

  belongs_to :rescue_group

  has_one :address, dependent: :destroy
  accepts_nested_attributes_for :address

end

app/models/rescue_group.rb
class RescueGroup < ActiveRecord::Base

  validates :name,
            :email_address,
            :contact,
            :emergency_contact, presence: true

  validates :phone_number, presence: true, format: { with: /\A\d{3}\-(\d{3})-(\d{4})\Z/, message: "must be in the format of 555-555-1212" }

  has_one :address, dependent: :destroy
  accepts_nested_attributes_for :address

  belongs_to :user
  has_many :shelters     # Each rescue_group usually deals with multiple shelters

  has_many :animals      # RescueGroups obviously deal with many animals. Each animal
                         # needs to have which rescue_group it came from originally,
                         # and, if needed, how many others were involved.

  has_many :pullers      # RescueGroups have people designated as (a) Puller(s) that go to the Shelter(s)
                         # to physically take control of the Animal(s).

  has_many :adopters, through: :animals # RescueGroups track Adopter(s) for Animal(s) through the Animal(s)

  has_many :trips # RescueGroups need to track Trip(s) in order to see where (a) Animal(s) went.

  has_and_belongs_to_many :transporters # A RescueGroup usually has many transporters associated with it
                                        # Note that (a) Transporter(s) can work with many RescueGroups
                                        # at the same time, showing on multiple RescueGroup rolls.

end

app/models/shelter.rb
class Shelter < ActiveRecord::Base

  validates :name,
            :phone_number,
            :contact_person, presence: true

  has_many :animals, dependent: :destroy  # Has many animals obviously. Also deals with multiple rescue_groups
                                          # but RARELY deals with transporters. Thats the rescue_group's job.
                                          # Also, the shelter doesn't list the rescue_groups. its just that many
                                          # rescue_groups happen to deal with the same shelter.
  accepts_nested_attributes_for :animals, reject_if: :all_blank, allow_destroy: true

  has_one :address, dependent: :destroy
  accepts_nested_attributes_for :address

  belongs_to :rescue_group
end

app/models/transporter.rb
class Transporter < ActiveRecord::Base

  validates :first_name,
            :last_name,
            :email_address,
            :primary_phone, presence: true

  validates_inclusion_of :paid_transport, :registered, in: [true, false]

  has_one :address
  accepts_nested_attributes_for :address

  has_and_belongs_to_many :rescue_groups  # more than one rescue_group they can transport for
                     # more than one rescue_group as well.
  has_many :trips    # handles many trips for different animals
  has_many :legs     # handles many legs for different trips

end

app/models/trip.rb
class Trip < ActiveRecord::Base


  has_one :start_address, foreign_key: "trip_id", class_name: "Address"
  has_one :end_address, foreign_key: "trip_id", class_name: "Address"

  validates_inclusion_of :paid_transport, in: [true, false]

  has_many :legs            # Usually a trip is broken down into legs, using multiple transporters
  has_many :transporters    # Usually, but not always, multiple transporters involved
  has_many :animals         # Usually, but not always, A animal sent, but can be more
  has_many :rescue_groups   # Usually A rescue_group involved, but can be more (cross-export)
  has_many :legs            # A trip can have 1 or many legs (depends how many drivers want to make the total trip)
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password

  ROLES_FOR_DISPLAY = { "RescueGroup" => "rescue_group",
                        "Transporter" => "transporter" }
  ROLES = ROLES_FOR_DISPLAY.values

  validates :role, inclusion: { in: ROLES, allow_blank: false }

  validates :username, presence: true, uniqueness: true

  validates :email_address, presence: true, uniqueness: true, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/ }

  validates :phone_number, presence: true, format: { with: /\A\d{3}\-(\d{3})-(\d{4})\Z/, message: "must be in the format of 555-555-1212" }

  validates :password, length: { minimum: 8 }

  has_many :rescue_groups, dependent: :destroy
  has_many :shelters, through: :rescue_groups, dependent: :destroy

  has_one :address, class_name: "Address", dependent: :destroy
  accepts_nested_attributes_for :address, allow_destroy: true

  scope :rescue_groups, -> { where(RescueGroup.where(user_id: self).load) }

end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/adopters_helper.rb
module AdoptersHelper
end

app/helpers/animals_helper.rb
module AnimalsHelper
end

app/helpers/legs_helper.rb
module LegsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/pullers_helper.rb
module PullersHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/shelters_helper.rb
module SheltersHelper
end

app/helpers/trips_helper.rb
module TripsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
 <title>
    <% if content_for?(:title) %>
        <%= yield(:title) %>
    <% else %>
        Animal Transporter Plus
    <% end %>
 </title>

  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!--[if lt IE 9]>
    <%= javascript_include_tag "bootstrap-ie" %>
  <![endif]-->

  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to "Zoie Plus", "/", :class => "navbar-brand" %>
      </div>
      <div class="collapse navbar-collapse">
        <ul class="nav navbar-nav">
          <li><a href="/about">About</a></li>
          <li><a href="/services">Transportation Services</a></li>
          <li><a href="/equipment">Transportation Equipment</a></li>
          <li><a href="/contact_us">Contact Us</a></li>
          <% if current_user %>
            <li><a href="/dashboard">Dashboard</a></li>
            <li><a href="/account">Account</a></li>
            <li><%= link_to "Sign Out", logout_path %>
          <% else %>
            <li><a href="/register">Register</a></li>
            <li><%= link_to "Sign In", login_path %></li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
  <div class="container">
    <% flash.each do |name, msg| %>
      <%= content_tag :div, :class => "alert alert-#{ name == :error ? "danger" : "success" } alert-dismissable" do %>
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
        <%= msg %>
      <% end %>
    <% end %>

    <%= yield %>

  </div>
  <div class="footer" font="small" align="center">
    Copyright &copy; 2013 CyberSpace Technologies Group. All Rights Reserved. <a href="https://www.gandi.net/ssl/secured/thezoieplus.com/45861/8db194129d"><%= image_tag("GANDI_SSL_logo_A_std_en.png") %></a>
  </div>
</body>
</html>